### ISSUE TITLE
Cannot set KCL consumer group on Spring Cloud Stream 2020.0.0

### ISSUE THREAD

**Issue by markathomas** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#156]
Trying to follow documentation on this:

```
spring.cloud.stream.kinesis.bindings.input-in-0.group=staging
spring.cloud.stream.kinesis.bindings.input-in-0.destination=staging-datastream
```
This does not work.  Nor does

```
spring.cloud.stream.kinesis.bindings.group=staging
spring.cloud.stream.kinesis.bindings.destination=staging-datastream
```

Basically, I'm looking for how to bind to `BinderProperties#setGroup`

**Comment by markathomas** [comment]
Found answer at https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/136 yet transferring to YAML does not work.  This does not work:
```
spring:
  cloud:
    stream:
      binding:
        input-in-0:
          group: staging
          destination: staging-datastream
```
