### ISSUE TITLE
Batch-Mode for Kinesis not working

### ISSUE THREAD

**Issue by pingrulez** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#162]
dependencies
---
'org.springframework.boot' version '2.3.10.RELEASE'
'springCloudVersion', "Hoxton.SR11"
'org.springframework.cloud:spring-cloud-stream-binder-kinesis:2.0.1.RELEASE'

application.yaml
```
spring:
  application:
    name: streamingService
  cloud:
    stream:
      kinesis:
        binder:
          kpl-kcl-enabled: true
      bindings:
        nsRequestOutputMessages-in-0:
          content-type: application/json
          group: notificationservice-ns-output-group
          destination: notificationservice-ns-output-stream
          consumer:
            batch-mode: true
```
Listener:
```
public class KinesisNSOutboundListener {
	
	@Bean
	Consumer<Message<byte[]>> nsRequestOutputMessages() {
		return message -> {	
			log.debug("Recieved NS Message: {}", new String(message.getPayload()));
		};
	}
	
//	@Bean
//	Consumer<List<byte[]>> nsRequestOutputMessages() {
//		ObjectMapper om = new ObjectMapper();
//		return list -> {
//			log.debug("Recieved NS Message: {}", list);
//		};
//	}

}
```
Issue:  Setting the batch-mode to true does not appear to make a difference.  Whether batch-mode is set to true or false, the Listener class is only receiving single messages.  If I uncomment code to use the List, I receive exceptions.

Is the batch-mode configuration for kinesis supported?  Maybe I need a different set of dependencies?

**Comment by pingrulez** [comment]
I'm not sure where Eclipse is reading properties, but when adding properties to my yaml file, listenerMode does not exist.
Is there a mismatch in dependencies and I am unknowingly using a new dependency?  Or maybe just ignore what my IDE is telling me?  

Thank you for such a fast response!

**Comment by artembilan** [comment]
Just ignore.

I'm investigating what is that new `batch-mode` and if we can support it on Kinesis binder level.

So, far your YAML should be like this:
```
spring:
  application:
    name: streamingService
  cloud:
    stream:
      kinesis:
        binder:
          kpl-kcl-enabled: true
        bindings:
          nsRequestOutputMessages-in-0:
            consumer:
              listenerMode: batch
      bindings:
        nsRequestOutputMessages-in-0:
          content-type: application/json
          group: notificationservice-ns-output-group
          destination: notificationservice-ns-output-stream
```
