### ISSUE TITLE
Aws Kinesisi binder app makes 1.3K calls to DDB 

### ISSUE THREAD

**Issue by kamalakannanvkp** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#180]
We have used spring-cloud-stream-binder-kinesis in our application to get data from kinesis. we have 4 shards for a kinesis and the spring boot app , reads from the stream , transform into other services.

**version used :** spring-cloud-stream-binder-kinesis:2.2.0

  **Issue:**
we see the calls made to the LockTable is always around 1.3K/Second even during the non-peak hours. 
<img width="1155" alt="Screenshot 2023-01-04 at 15 01 45" src="https://user-images.githubusercontent.com/8424867/210584089-fa513e3f-4268-4469-bcb9-7680ff9dfcd9.png">

**X-ray metrics:** 
![image](https://user-images.githubusercontent.com/8424867/210582200-489400aa-15eb-45af-9dbc-336935e2cd7d.png)

Configurations:
As part of the enhancement activity , we have tweaked the lock table settings from default to below , but it did not help as well.

```
spring:
  cloud:
    stream:
      binders:
        kinesis:
          type: kinesis
        sqs:
          type: sqs
        sns:
          type: sns
      kinesis:
        binder:
          checkpoint:
            table: VPA.MetadataStoreTable
          locks:
            table: VPA.LockRegistryTable
            leaseDuration: 300
            heartbeatPeriod: 60
          auto-create-stream: false

```

we notice a bump in our AWS cost with this table around $300 for a month. Please let me know if any other infomation/metrics needed, i can pull out to sort this out.
