### ISSUE TITLE
Two consumes in a Consumer group 

### ISSUE THREAD

**Issue by dhruvpanwar95** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#36]
I have two instances of my application in which i have given same consumer group name. However, there is inconsistency in consumption of messages. Sometimes it consumes equal messages. However, Sometimes the consumption message count is more (I am suspecting both consumers are consuming same message). I have only one shard.

application.yaml

```
spring:
  cloud:
    stream:
      bindings:
        ordersOut:
          destination: testhk
          content-type: application/json
        ordersIn:
          group: hel1
          destination: testhk
          content-type: application/json
```
