### ISSUE TITLE
Consumer pauses processing messages in between suddenly for some sometime

### ISSUE THREAD

**Issue by vikrantch-hk** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#47]
![put records](https://user-images.githubusercontent.com/34442831/37814107-39b0f9d4-2e8e-11e8-8649-78fa21797bd6.JPG)
![get records](https://user-images.githubusercontent.com/34442831/37814123-59a75b7a-2e8e-11e8-8b13-a3c7e081a2e7.JPG)

Hi team,
We are facing a weird issue where consumer did not pick messages for sometime although in getrecords is getting hit continuously and there are messages in stream , this happens for sometime after few restarts again system behaves properly not sure where is the problem, there is no exception in the logs. Below are the logs for kinesis getRecords 

``` 
amz-sdk-invocation-id:ae00d212-858a-0ec0-a0b1-e9d409cc79ba
amz-sdk-retry:0/0/500
content-length:251
content-type:application/x-amz-cbor-1.1
host:kinesis.ap-south-1.amazonaws.com
user-agent:aws-sdk-java/1.11.125 Linux/2.6.32-696.10.1.el6.x86_64 OpenJDK_64-Bit_Server_VM/25.161-b14/1.8.0_161
x-amz-date:20180323T054355Z
x-amz-target:Kinesis_20131202.GetRecords

amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target
73351c9a04a09b20456711d1e59173255c1e2898b2078615ea3892be9ddbe567"
2018-03-23 11:13:55.929 DEBUG 13601 --- [esis-consumer-1] com.amazonaws.auth.AWS4Signer            : AWS4 String to Sign: '"AWS4-HMAC-SHA256
20180323T054355Z
20180323/ap-south-1/kinesis/aws4_request
f9fd57041d5ef4d46dfb95eda89a16af855fdfac9f0e9e1a79de43da4b0ad795"
2018-03-23 11:13:55.972 DEBUG 13601 --- [esis-consumer-1] com.amazonaws.request                    : Received successful response: 200, AWS Request ID: db967db4-a143-4842-88b8-eb5c70051b80
2018-03-23 11:13:55.972 DEBUG 13601 --- [esis-consumer-1] com.amazonaws.requestId                  : x-amzn-RequestId: db967db4-a143-4842-88b8-eb5c70051b80

```

**Comment by vikrantch-hk** [comment]
![image](https://user-images.githubusercontent.com/34442831/37814157-9dbbafb4-2e8e-11e8-9a15-033d5879af9a.png)
attaching screen shot where system picked the messages, messages were put in stream around 11 am, they were processed around 11:30 am although getrecords method was getting called continuously.

**Comment by artembilan** [comment]
If you say the `getRecords()` is hit from the `KinesisMessageDrivenChannelAdapter`, so why do you think it is the problem of this project, but not something in the AWS Kinesis per se?

Have you tries to reach their support?

There is not AWS engineers here. Sorry.

**Comment by vikrantch-hk** [comment]
@artembilan yes I have raised a ticket with AWS support also, but they are not as prompt as Spring guys , will update thread after receiving response from them, thanks :)

**Comment by vikrantch-hk** [comment]
@artembilan I got below response from aws support and it seems to be because of TRIM_HORIZON iterator type 

```
 the time-lag is an expected behavior from the shardIterator which is set to the TRIM-HORIZON. Generally, TRIM_HORIZON causes ShardIterator to point to the last untrimmed record in the shard in the system (the oldest data record in the shard). So the getRecords() will move from that point to the last point, which takes time. It is by default 1 day and it can be extended to 7 days. As you mentioned you have used the default settings. So for example, if the getRecord() wants to start reading records, it will start from 24 hours ago, and moves to reaches the current point. Please check out different types of the shardIterator to make sure you are using the one that suits your case[1].
```

I tried to change iterator type to 'latest' using below configuration but application is still using TRIM_HORIZON as iterator type below are the yaml changes and startup logs 

```
spring:
  cloud:
    stream:
      bindings:
        orderPushChannel:
          group: orderPushGroup
          destination: devStreamvikrant
          content-type: application/x-java-object
          consumer:
            partitioned: true
            shardIteratorType: LATEST
          enabled: true
```

startup logs 

```
2018-03-29 11:27:36.781  INFO 4308 --- [  restartedMain] a.i.k.KinesisMessageDrivenChannelAdapter : started KinesisMessageDrivenChannelAdapter{shardOffsets=[KinesisShardOffset{iteratorType=TRIM_HORIZON, sequenceNumber='null', timestamp=null, stream='devStreamvikrant', shard='shardId-000000000000', reset=false}], consumerGroup='orderPushGroup'}

```

**Comment by vikrantch-hk** [comment]
ok my bad it worked with below config

```
cloud:
    stream:
      kinesis:
        bindings:
          orderPushChannel:
            consumer:
              shardIteratorType: LATEST #AT_SEQUENCE_NUMBER:49582864779258502844112880033325043705276066205540548610
    ```
