### ISSUE TITLE
How can i reread all messages from a stream for the same consumer group?

### ISSUE THREAD

**Issue by YuriyBarvenko1234** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#61]
Hello,

i try to read all messages from kinesis stream.  But it's only work ones for new consumer group. but how can i reread one more all messages?

i try to put in configuration samthing like this. shardIteratorType: AFTER_SEQUENCE_NUMBER:0

```
 kinesis:
        bindings:
          ordersOut:
            producer:
              #set to true in test, because we dont want to wait too long
              sync: true
          ordersIn:
            consumer:
              # In tests we always want to start reading from the start
              shardIteratorType: AFTER_SEQUENCE_NUMBER:0
```

              

but it's dose not work.

Can somebody help me?
