### ISSUE TITLE
trim_horizon not working as documented:

### ISSUE THREAD

**Issue by fireboy1919** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#63]
Here's the spring cloud config I'm using:
```
  cloud:
    stream:
      kinesis:
        binder:
          autoAddShards: true
          minShardCount: 1
          checkpoint.table: ecommKinesis
          locks:
            table: ecommLocks
            timeToLive: 2000
            leaseDuration: 500
          listenerMode: batch

      bindings:
        input:
          destination: ecomm_email_stream
          consumer:
            idleBetweenPolls: 10000
            checkpointMode: batch
            shardIteratorType: TRIM_HORIZON
```
Key output from the log when there is not yet any ecommKinesis or ecommLocks table (or even after, actually):
018-09-12 23:56:10.134  INFO 1 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : The [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=LATEST, sequenceNumber='null', timestamp=null, stream='ecomm_email_stream', shard='shardId-000000000000', reset=false}, state=NEW}] has been started.

Is the documentation wrong?  Why is the KinesisMessageDrivenChannelAdapter being created with the LATEST type iterator instead of the one that I specified?

**Comment by fireboy1919** [comment]
Here's the spring cloud config I'm using:
```
  cloud:
    stream:
      kinesis:
        binder:
          autoAddShards: true
          minShardCount: 1
          checkpoint.table: ecommKinesis
          locks:
            table: ecommLocks
            timeToLive: 2000
            leaseDuration: 500
          listenerMode: batch

      bindings:
        input:
          destination: ecomm_email_stream
          consumer:
            idleBetweenPolls: 10000
            checkpointMode: batch
            shardIteratorType: TRIM_HORIZON
```
Key output from the log when there is not yet any ecommKinesis or ecommLocks table (or even after, actually):
018-09-12 23:56:10.134  INFO 1 --- [esis-consumer-1] a.i.k.KinesisMessageDrivenChannelAdapter : The [ShardConsumer{shardOffset=KinesisShardOffset{iteratorType=LATEST, sequenceNumber='null', timestamp=null, stream='ecomm_email_stream', shard='shardId-000000000000', reset=false}, state=NEW}] has been started.

Is the documentation wrong?  Why is the KinesisMessageDrivenChannelAdapter being created with the LATEST type iterator instead of the one that I specified?

**Comment by fireboy1919** [comment]
After tracing through the code live, it looks like the binder config doesn't quite match the documentation.
This is what will actually make it work:
```
  cloud:
    stream:
      kinesis:
        binder:
          autoAddShards: true
          minShardCount: 1
          checkpoint.table: ecommKinesis
          locks:
            table: ecommLocks
            timeToLive: 2000
            leaseDuration: 500
        bindings:
          input:
            consumer:
              idleBetweenPolls: 10000
              checkpointMode: batch
              shardIteratorType: TRIM_HORIZON
      bindings:
        input:
          destination: ecomm_email_stream
```

The producer has a similar error; I was banging my head about getting groups to work because of this bug.

**Comment by artembilan** [comment]
Because the property must be `spring.cloud.stream.kinesis.bindings.input.consumer.shardIteratorType`, but in your case the `kinesis` branch is missed.
Something like this:
```
cloud:
  stream:
    kinesis:
      binder:
        autoAddShards: true
        minShardCount: 1
        checkpoint.table: ecommKinesis
        locks:
          table: ecommLocks
          timeToLive: 2000
          leaseDuration: 500
        listenerMode: batch
      bindings:
        consumer:
          idleBetweenPolls: 10000
          checkpointMode: batch
          shardIteratorType: TRIM_HORIZON
    bindings:
      input:
        destination: ecomm_email_stream
```

I believe this convenient YAML configuration becomes not so convenient...
