### ISSUE TITLE
Properties as aws system variables

### ISSUE THREAD

**Issue by sidath80** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#66]
Hi Team,

How can I pass this  properties as system variables, We are planning to put this into the AWS environment variable.

Your help is really appreciated.

```
spring:
  cloud:
    stream:
      bindings:
        ordersOut:
          destination: dev_stream
```

Thanks
Sidath
