### ISSUE TITLE
Support different AWS accounts for producer and consumer

### ISSUE THREAD

**Issue by jorgefr** [spring-cloud/spring-cloud-stream-binder-aws-kinesis#74]
Since the library supports having 2 resources, input and output stream, it is possible that each resource is defined in a different AWS account. Are there any plans to support this scenario soon?

I'm using version 1.0.0.M1 but it looks like the same behaviour is implemented for the 1.0.0.RELEASE.

Thanks!

**Comment by artembilan** [comment]
This has been fixed with the https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/a2b730e48d220afcd585ae9cb1461022ae1daf33.

Please, try your solution using `1.1.0.BUILD-SNAPSHOT`, but don't forget to configure properly a multi-binder environment for both `input` and `output` destinations.

And come to us with the feedback to close this issue respectively or let us know what doesn't work and we'll see what and how we can fix yet.

Thanks

**Comment by jorgefr** [comment]
Thanks for the quick answer @artembilan. I'll try to test it, thought it might take a while until I can test it. In the meanwhile we already implemented a workaround.

**Comment by artembilan** [comment]
Sounds great!

May we know here what is that workaround, please?

**Comment by jorgefr** [comment]
By the way, I only see M1 release of `spring-cloud-starter-stream-kinesis` in maven: https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-stream-kinesis. however, for the binder, the RELEASE version is already there.

Is the starter going to have a release soon? do you know? I don't even find the Github repo for it.

**Comment by artembilan** [comment]
@jorgefr ,

Thank you for feedback and sharing your experience with different `AmazonKinesisAsync`!
Not sure how to proceed from here, but the point with `ContextCredentialsAutoConfiguration` on the `KinesisBinderConfiguration` is about a multi-binder support: https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#multiple-binders

So, you configure one Kinesis binder in your YAML file for the consumer side on the `input` destination and the second one for the producer side.
The difference in the configuration properties is achieved with the `environment` property where you can configure different `cloud.aws.credentials.accessKey` and `cloud.aws.credentials.secretKey` for both of them: https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.0.1.RELEASE/single/spring-cloud-aws.html#_configuring_credentials

Which, essentially, are just Spring Boot configuration properties for Spring Cloud AWS auto-configuration.

We need to think more how to allow to configure some custom `CredentialsProvider` for the particular binder in the multi-binder environment...

**Comment by artembilan** [comment]
Regarding a `spring-cloud-starter-stream-kinesis`: we don't provide such an artifact any more because it doesn't bring any value.
What you need is just direct usage of the `spring-cloud-stream-binder-kinesis` artifact.

**Comment by artembilan** [comment]
@jorgefr ,

Regarding the custom `AmazonKinesisAsync`: https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/htmlsingle/#howto-externalize-configuration

So, you can have a `@Configuration` class with that `AmazonKinesisAsync` bean and use the configuration class to specify in the `spring.main.sources` property under binder's `environment`:
```
 binders:
        kinesisProducer:
          type: kinesis
          environment:
            spring:
              main:
                sources: com.my.config.CustomAmazonKinesisConfiguration
```

Does it make sense to you?

**Comment by jorgefr** [comment]
Hi @artembilan so this is all new to me, so cannot say if it makes sense 😄 

But I tried to run the application with that config as you suggested:

```
spring.cloud.stream:
  bindings:
    input:
      destination:my-input-stream
    output:
      destination: my-output-stream
      binder: kinesisProducer
  binders:
    kinesisProducer:
      type: kinesis
      defaultCandidate: false
      environment:
        spring:
          main:
            sources: my.config.KinesisOutputConfiguration
```

`KinesisOutputConfiguration` defines the second `AmazonKinesisAsync` bean with the `AssumeRoleCredentialsProvider`.

And it worked. the stream was described successfully! 🎉 

But what effect does it have in the application to define the environment for that binder? does the binder receive its own application context?

Should the `KinesisOutputConfiguration` be defined out of the scope of the main application context so it doesn't get picked up automatically on app startup?

**Comment by artembilan** [comment]
That's great feedback, @jorgefr !

So, sounds like we still have a consistent model and use binder as much as possible! 😄 

I think you are right, that this custom `@Configuration` should not be visible for the *main* application context since it is only specific for particular binder.
I'm not sure that it is going to work if you remove `@Configuration` annotation from that configuration class...

I think you can play with the `@Profile` and activate it from that ` environment:` as well via an appropriate Spring Boot configuration property: https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/htmlsingle/#boot-features-adding-active-profiles
This way it is not going to be visible for the main application context and will work only from the particular binder.

**Comment by jorgefr** [comment]
Hi @artembilan 

Thanks for the tip. 
I have to say that it was actually working when I removed `@Configuration` from the class, but I didn't like it that much
So I tried with `@Profile` and several options to configure the profile under `environment` but none worked. The one with which I got closest was:

```
      environment:
        spring:
          main:
            additionalProfiles: rrs
```

I saw that the property is added to the context, but after the environment is prepared, so the class doesn't get picked up. I found that out by debugging. Inside `org.springframework.boot.SpringApplication#prepareEnvironment`, I could see that the environment is prepared, and then, the property is bound, by calling `bindToSpringApplication`. I'm using `spring-boot-2.0.3.RELEASE`.

However, I got a similar result by using the `excludeFilters` from `@ComponentScan`.

The only weird thing that I see, is that the bean method is called twice. With a lot of debugging, I found that after the new `SpringApplication` is run from `org.springframework.cloud.stream.binder.DefaultBinderFactory#getBinderInstance`. Everything works as expected until the environment is prepared. (same method as above). 

1. At that point, `ApplicationEnvironmentPreparedEvent` is sent, 
2. BootstrapApplicationListener` creates a new context by running `SpringApplication.run()` again.
3. It processes my config class, since the `sources` is available (`DefaultBinderFactory#getBinderInstance` added it as a command line argument), and creates an instance of `AmazonKinesisAsync`.
4. After the event is processed, the context creation initiated by `DefaultBinderFactory#getBinderInstance` resumes the execution and this one processes your `KinesisBinderConfiguration`, instantiating the `ProvisioningProvider` and the rest of the beans, including another instance of `AmazonKinesisAsync`, since the one instantiated before belongs to a different context.

So my conclusions are that:

1. For the first attempt, either I need more things to configure the profiles, or the profiles are not being loaded properly.
2. For the second approach, it is weird that `BootstrapApplicationListener` gets invoked and creates an unnecessary instance of `AmazonKinesisAsync`. But I don't know about this context loading and bootstrap listener in `SpringBoot`.

But the important thing for me, is that your solution is working! 🎉 . Thank you very much!

**Comment by jorgefr** [comment]
Agree. For us it works also fine. Didn't see any important side effects so far, but I'll try to reproduce this problem with a smaller sample project to be able to reproduce the problem and ask in the respective projects to find out where is actually the flaw.

Thanks a lot for the help!

**Comment by ennala** [comment]
Hi Guys I am facing a similar situation. I am trying to write to a cross region aws account.
I understood on how to use AssumeRoleCredentialsProvider.. but not able to figure out how to specify a different region for the binder. Appreciate any help.

**Comment by ameneghello** [comment]
Hi @aclement, I would like to reopen the topic to add another more complex case scenario. **Two Kinesis streams in two different AWS accounts** and have one consumer stream (as well as one producer) for each account.
In Summary:
	▪	ConsumerA -> StreamA -> AWSAccount1
	▪	ProducerA -> StreamA -> AWSAccount1
	▪	ConsumerB -> StreamB -> AWSAccount2
	▪	ProducerB -> StreamB -> AWSAccount2

We are using 
	▪	spring-cloud-stream-binder-kinesis = **2.0.0.RELEASE**
	▪	spring-boot = **2.2.5.RELEASE**
	▪	**Java13**

The _application.yaml_ is

```
spring:
  application:
    name: sample-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        consumer-a-channel-input:
          group: "sample-service"
          destination: "stream-a"
          binder: streamABinder
        producer-a-channel-output:
          destination: "stream-a"
          binder: streamABinder
        consumer-b-channel-input:
          group: "sample-service"
          destination: "stream-b”
          binder: streamBBinder
        producer-b-channel-output:
          destination: "stream-b”
          binder: streamBBinder
      kinesis:
        binder:
          headers: type,version
        bindings:
          producer-a-channel-output:
            producer:
              sync: true
              sendTimeout: 10000
              partitionKeyExpression: payload.id
          producer-b-channel-output:
            producer:
              sync: true
              sendTimeout: 10000
              partitionKeyExpression: payload.id
          consumer-a-channel-input:
            consumer:
              shardIteratorType: TRIM_HORIZON
          consumer-b-channel-input:
            consumer:
              shardIteratorType: TRIM_HORIZON
      binders:
        streamABinder:
          type: kinesis
          defaultCandidate: false
          environment:
            spring:
              main:
                sources: com.sample.org.config.SampleConfigA
        streamBBinder:
          type: kinesis
          defaultCandidate: false
          environment:
            spring:
              main:
                sources: com.sample.org.config.SampleConfigB

account1:
    region: eu-west1

account2:
    userid: AKIAKJHSGQAGO7NLLDVSY
    password: S/he+YG0HFDSlU7NU9+xtZ8chIH/hsjhfgd
    region: eu-central1 
```

**Notes**:
	▪	`allow-bean-definition-overriding` is needed to override some of the beans defined in the KinesisBinderConfiguration (e.g. AmazonDynamoDBAsync)
	▪	`account2.userid` and `account2.password` should be stored in a secure location this is only for the exercise purpose
	▪	account1 will use the `aws.accessKeyId` and `aws.secretKey` in the profile file

```
@Configuration
public class SampleConfigA {

    @Value("${account1.region}")
    private String region;

    @Bean
    @Primary
    public AmazonKinesisAsync amazonKinesis(AWSCredentialsProvider awsCredentialsProvider) {
        return AmazonKinesisAsyncClientBuilder.standard()
                .withCredentials(awsCredentialsProvider)
                .withRegion(region)
                .build();
    }

    @Bean
    @Primary
    AWSCredentialsProvider awsCredentialsProvider() {
        return new DefaultAWSCredentialsProviderChain();
    }

    @Bean
    @Primary
    AmazonDynamoDBAsync amazonDynamoDBAsync(AWSCredentialsProvider awsCredentialsProvider) {
        return AmazonDynamoDBAsyncClientBuilder.standard()
                .withCredentials(awsCredentialsProvider)
                .withRegion(this.region)
                .build();
    }
}
```

**Notes**:
	▪	The `@Primary` annotation is to have the priority of the Bean definition instead the `KinesisBinderConfiguration`
	▪	The `AmazonDynamoDBAsync` is necessary because the `KinesisBinderConfiguration` has the check this.hasInputs equals to false with the custom binders streamABinder and streamBBinder

```
@Configuration
public class SampleConfigB {

    @Value(“${account2.region}")
    private String region;

    @Value("${account2.userid}")
    private String user;

    @Value("${account2.password}")
    private String password;


    @Bean(destroyMethod = "shutdown")
    public AmazonKinesisAsync amazonKinesis() {
        return AmazonKinesisAsyncClientBuilder
                .standard()
                .withCredentials(createStsAssumeRoleCredentialsProvider())
                .withRegion(region)
                .build();
    }

    private AWSCredentialsProvider createStsAssumeRoleCredentialsProvider() {
        BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(user, password);
        return new AWSStaticCredentialsProvider(basicAWSCredentials);
    }

    @Bean
    @Primary
    AmazonDynamoDBAsync amazonDynamoDBAsync(@Value(“${account1.region}") String region) {
        return AmazonDynamoDBAsyncClientBuilder.standard()
                .withCredentials(new DefaultAWSCredentialsProviderChain())
                .withRegion(region)
                .build();
    }

}

```
**Notes**:
	▪	the `SampleConfigB` setup the Kinesis stream for the ConsumerB and ProducerB on the **AWSAccount2**. The `SpringIntegrationMetadataStore` and `SpringIntegrationLockRegistry` for the ConsumerB will use the **AWSAccount1**. This is currently a limitation as there is only one AmazonDynamoDBAsync bean.
We haven't found other issues at the moment, could you advise about this configuration if it is going to be supported by future releases.
